# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: cirocioppa
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: beacon
# serverless.yml

service: apollo-lambda
useDotenv: true
provider:
    name: aws
    runtime: nodejs14.x
    #allows lambda function to access ec2
    iamRoleStatements:
        - Effect: "Allow"
          Action: "*"
          Resource: "*"
functions:
    graphql:
        # this is formatted as <FILENAME>.<HANDLER>
        handler: serverless/index.handler
        events:
            - http:
                  path: /
                  method: post
                  cors: true
            - http:
                  path: /
                  method: get
                  cors: true
    manager:
        handler: serverless/functions/manager.handler
        events:
            - schedule: rate(5 minutes)

plugins:
  - serverless-offline
custom:
    serverless-offline:
        noPrependStageInUrl: true
